version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    groups:
      major:
        update-types:
          - "major"
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"
    schedule:
      interval: "monthly"
      time: "10:00"
      timezone: "Asia/Tokyo"
    cooldown:
      # リリースから7日が経過していないパッケージは更新しない
      default-days: 7

  - package-ecosystem: "github-actions"
    directory: "/"
    groups:
      github-actions:
        patterns:
          - "*"
    schedule:
      interval: "monthly"
      time: "10:00"
      timezone: "Asia/Tokyo"
    cooldown:
      # リリースから7日が経過していないパッケージは更新しない
      default-days: 7
