version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    groups:
      dependencies:
        patterns:
          - "*"
    schedule:
      # 毎週月曜日
      interval: "weekly"
      day: "monday"
    cooldown:
      # リリースから30日が経過していないパッケージは更新しない
      default-days: 30

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # 毎週月曜日
      interval: "weekly"
      day: "monday"
    cooldown:
      # リリースから30日が経過していないパッケージは更新しない
      default-days: 30
