ignoredBuiltDependencies:
  - esbuild
  - unrs-resolver

onlyBuiltDependencies:
  - esbuild
  - unrs-resolver

patchedDependencies:
  "@aws-cdk/integ-tests-alpha": patches/@aws-cdk__integ-tests-alpha.patch

# 30 days (30 * 24 * 60 = 43200 minutes)
minimumReleaseAge: 43200
