minimumReleaseAge: 43200 # 30 days (30 * 24 * 60 = 43200 minutes)

onlyBuiltDependencies:
  - esbuild
  - unrs-resolver

patchedDependencies:
  "@aws-cdk/integ-tests-alpha@2.215.0-alpha.0": patches/@aws-cdk__integ-tests-alpha@2.215.0-alpha.0.patch
