ignoredBuiltDependencies:
  - esbuild
  - unrs-resolver

onlyBuiltDependencies:
  - esbuild
  - unrs-resolver

patchedDependencies:
  "@aws-cdk/integ-tests-alpha": patches/@aws-cdk__integ-tests-alpha.patch
