# dependabot PR 作成時に test と cdk diff を実行して確認する

name: dependabot-pr-check

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  dependabot-pr-check:
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    runs-on: ubuntu-latest
    permissions:
      # AWS 認証に OIDC を使用するため
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }} # PR の HEAD をチェックアウトする

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-1
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}

      - name: Test
        run: pnpm run test

      - name: Cdk diff check
        run: pnpm run cdk diff --fail true # 差分がある場合はエラーを返す
        env:
          LINE_CHANNEL_ID: ${{ secrets.LINE_CHANNEL_ID }}
          LINE_CHANNEL_SECRET: ${{ secrets.LINE_CHANNEL_SECRET }}
          LINE_USER_ID: ${{ secrets.LINE_USER_ID }}
          EXCHANGE_RATE_API_KEY: ${{ secrets.EXCHANGE_RATE_API_KEY }}
          OUTPUT_GRAPH: "false"
