name: dependabot-pr-check-trigger

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  pr-check-trigger:
    if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Pull request from dependabot"
