name: dependabot-pr-check

on:
  # dependabot が PR を作成したとき
  workflow_run:
    workflows: ["dependabot-pr-check-trigger"]
    types:
      - completed

jobs:
  pr-check:
    # dependabot の PR 作成による直接のトリガーは除外する
    if: ${{ !(github.event_name == 'pull_request' && github.actor == 'dependabot[bot]') }}
    runs-on: ubuntu-latest
    permissions:
      # AWS 認証に OIDC を使用するため
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }} # PR の HEAD をチェックアウトする

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-1
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}

      - name: Test
        run: pnpm run test

      - name: Cdk diff check
        run: pnpm run cdk diff -- --fail true # 差分がある場合はエラーを返す
